name: Bug Report
description: Report a bug or unexpected behavior in the ClickUp IntelliJ Plugin
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue! Please fill out the information below to help us reproduce and fix the bug.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Open IntelliJ IDEA
        2. Navigate to...
        3. Click on...
        4. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: dropdown
    id: ide
    attributes:
      label: IDE
      description: Which JetBrains IDE are you using?
      options:
        - IntelliJ IDEA Ultimate
        - IntelliJ IDEA Community
        - PhpStorm
        - WebStorm
        - PyCharm Professional
        - PyCharm Community
        - RubyMine
        - CLion
        - GoLand
        - DataGrip
        - Rider
        - Android Studio
        - AppCode
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: ide-version
    attributes:
      label: IDE Version
      description: "Example: 2024.3.1, 2025.1"
      placeholder: "2024.3.1"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: You can find this in Settings → Plugins → Installed
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Example: macOS 14.2, Windows 11, Ubuntu 22.04"
      placeholder: "macOS 14.2"

  - type: input
    id: java-version
    attributes:
      label: Java/JVM Version
      description: "You can find this in Help → About or by running `java -version`"
      placeholder: "17.0.9"

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces
      description: |
        Please attach relevant logs or stack traces. You can find IDE logs in Help → Show Log in Finder/Explorer.
        Tip: You can attach files by dragging and dropping them into this field.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (related plugins, project setup, etc.).

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution (Optional)
      description: If you have suggestions on how to fix the bug, please describe them here.
