name: Tag

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

permissions:
  contents: write # for creating tags

jobs:
  analyze-coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Check coverage
        id: check-coverage
        run: |
          COVERAGE=$(grep -oP 'Total.*?\K\d+\.\d+' coverage-report/index.html)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage is insufficient to continue"
            exit 1
          fi

  generate-tag:
    runs-on: ubuntu-latest
    needs: analyze-coverage

    steps:
      - uses: actions/checkout@v4

      - name: Generate and push semver tag
        if: steps.check-coverage.outcome == 'success'
        run: ./gradlew pushSemverTag -Psemver.stage=auto -Psemver.scope=auto